### ISSUE TITLE
download_file for a specific file

### ISSUE THREAD

**Issue by benmarwick** [chartgerink/osfr#31]
I'm trying to get one file, `dc_arch.rds`, from my private osf repo. I can't see how to specify only this file. So far I've tried this:

```
library(osfr)
dc_arch <- download_file("osf.io/tsm89", private = TRUE)
```

but I get 

```
Error in download_file("osf.io/tsm89", private = TRUE) : Failed. Are you sure you have access to the file?
```

I have a token which I provided to the R session. How can I make this work?

**Comment by chartgerink** [comment]
Sorry for the confusion, you only need to input the id as argument, not the `osf.io/` part. So this should work if you have your PAT specified.
```R
dc_arch <- download_file("osf.io/tsm89", private = TRUE)
```
Did the documentation confuse you? I was looking at it now and can imagine that the text `Specify the node id (osf.io/XXXX)` is somewhat ambiguous.

**Comment by benmarwick** [comment]
Thanks for your quick reply, that does solve the problem, to remove the `osf.io/` from the `id = ` argument. 

One other thing, the `download_file` function doesn't appear to have any code to use the `path = ` argument, and gives an error if I supply a path. May I suggest this fix (indicated by `# BM`)?

```
config <- get_config(private)
url_osf <- construct_link(paste0("guids/", id))
call <- httr::GET(url_osf, config)
if (!call$status_code == 200) 
  stop("Failed. Are you sure you have access to the file?")
res <- process_json(call)
if (is.null(path)) {
  txt <- res$data$attributes$name
  start <- utils::tail(gregexpr("/", txt)[[1]], 1)
  end <- nchar(txt)
  file <- substr(txt, start + 1, end)
# BM: let's use the path argument 
} else {
  file <- paste0(path, res$data$attributes$name)
# BM: end of my suggestion
}
message(paste0("Saving to filename: ", file))
call <- httr::GET(res$data$links$download, config, httr::write_disk(file, 
                                                                    overwrite = TRUE))
if (call$status_code != 200) 
  stop("Failed to download file.")
message("Successfully downloaded file.")
return(file)
```

**Comment by chartgerink** [comment]
Oh @benmarwick you marvelous person, these kinds of things always happen over time. Thanks for picking that up! I can add it, but maybe it would be best that you do a quick PR for this? Don't want your contribution to be glossed over in the future! [Here's an edit link](https://github.com/chartgerink/osfr/edit/master/R/files.R#L296) if you'd want to. Otherwise I'll make the adjustment.

**Comment by benmarwick** [comment]
Thanks, no worries, I've made a PR (#32). I had a look through the tests and saw that a test for `download_file` was [commented out](https://github.com/chartgerink/osfr/blob/master/tests/testthat/test-operations.R#L91). Just thought I'd check with you about that before doing anything.

**Comment by chartgerink** [comment]
Yea that was due to a local file that wouldn't run otherwise. Leaving that out until I work on that again.
