### ISSUE TITLE
Mismatch btw OSF and OSFr defaults for privacy on newly created projects

### ISSUE THREAD

**Issue by csoderberg** [chartgerink/osfr#34]
When you create a project on the OSF, the default setting is 'private', whereas for osfr when you create a project through the package the default setting is 'public'. People may not realize this unless they read the documentation very carefully. To reduce possible confusion, would you considering switching the default? Or, perhaps making it so there is no default and people must put in their project/component creation functions whether they want it to be public or private?

**Comment by chartgerink** [comment]
Yes, thanks, will definitely make this consistent! As you might notice, I really need to get back working on this project.

What do you think is more reasonable to be the default; public or private?

**Comment by csoderberg** [comment]
Given that when you make a project on the OSF it defaults to private, I would say that a 'private' default for the function is probably more reasonable to avoid confusion. But, you could also just make privacy_setting a required input for the function so that people have to make an active choice (public or private) whenever they create a new through the package?

**Comment by chartgerink** [comment]
Everything is updated for posting to the OSF in commit aa1daee4d8f805a275b2f10e3746fbb4ecb68065

Thanks again Courtney! Finally got back to this.
