### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by chartgerink** [chartgerink/osfr#36]
In order to streamline contributions, I would like to add a `CONTRIBUTING.md`. However, R doesn't have a standard styleguide as JS, so I'm struggling a bit with the specifications to use here. Some I (try to) use already:

1. Use 2 spaces, no tabs.
2. Curly braces start on the same line as e.g. an `if` statement, but end on their own line. 

Suggestions for others, please discuss here (hopefully this doesn't end up being a flame war on tabs v spaces)

**Comment by naupaka** [comment]
Over at Software Carpentry, we generally try to have folks follow the [Google R style guide](https://google.github.io/styleguide/Rguide.xml) and Hadley's [guide from Advanced R](http://adv-r.had.co.nz/Style.html).

**Comment by chartgerink** [comment]
Thanks @naupaka, that sounds like a good tip. I always forget about Hadley's guide. It is a bit a shame that the two are somewhat conflicting (e.g., naming in camelCase good according to Google, bad according to Hadley).

I'll stick to Hadley's for the CONTRIBUTING.md
